DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: dgcnn_projnet_1_run_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: projnet
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
